import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SignUpModal from "@/shared/components/Modals/AuthModal";
import ReactQueryProvider from "@/processes/tanstack/ReactQueryProvider";
import AddProeprtyModal from "@/shared/components/Modals/AddProeprtyModal";
import SearchModal from "@/shared/components/Modals/SearchModal";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "DjangoBnb",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Navbar />
                <ReactQueryProvider>
                    <div className="pt-32">{children}</div>
                    <SearchModal />
                    <SignUpModal />
                    <AddProeprtyModal />
                </ReactQueryProvider>
            </body>
        </html>
    );
}
